global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'zephyr-backend'
    static_configs:
      - targets: ['host.docker.internal:4000']  # Docker host.docker.internal resolves to host machine
    metrics_path: '/metrics'
    scrape_interval: 10s
